version: '3'
services:
  nginx:
      image: nginx:latest
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ./wwwroot/html:/usr/share/nginx/html
          - ./wwwroot/nginx.conf:/etc/nginx/nginx.conf

  authDB:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - authDB:/var/lib/mysql

  shopDB:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - shopDB:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8082:80
      environment:
        - PMA_ARBITRARY=1

  redis:
    image: redis:alpine
    container_name: redis_db
    ports:
      - 6379:6379 
    restart: always
    volumes:
          - ./redis/data:/data
  
  rabbitmq:
    image: rabbitmq:management

    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=root

  # backend:
  #   build: ./server/
  #   container_name: backend
  #   ports:
  #       - "8080:8080"

  # frontend:
  #   image: node:16
  #   container_name: frontend
  #   volumes:
  #     # Mount the root folder that contains .git
  #     - .:/workspace:cached
  #   command: /bin/sh -c "while sleep 1000; do :; done"
  #   links:
  #     - backend
  #   # ...

volumes:
  authDB:
  shopDB: